### PR TITLE
Fix #542

### LINKED ISSUE #542: Bug: VmAbstract.mutableAttributesInit() overwrites CloudletScheduler passed in constructor
## Description

When creating a `VmSimple` (or any Vm subclass) with a specific `CloudletScheduler`, the scheduler is silently overwritten by `mutableAttributesInit()` in the `VmAbstract` constructor.

## Steps to Reproduce

1. Create a `VmSimple` with `CloudletSchedulerSpaceShared`:
```java
package org.cloudsimplus.examples;

import org.cloudsimplus.brokers.DatacenterBrokerSimple;
import org.cloudsimplus.cloudlets.CloudletSimple;
import org.cloudsimplus.core.CloudSimPlus;
import org.cloudsimplus.datacenters.DatacenterSimple;
import org.cloudsimplus.hosts.HostSimple;
import org.cloudsimplus.resources.PeSimple;
import org.cloudsimplus.schedulers.cloudlet.CloudletSchedulerSpaceShared;
import org.cloudsimplus.utilizationmodels.UtilizationModelDynamic;
import org.cloudsimplus.vms.VmSimple;

import java.util.List;

/**
 * Minimal example to demonstrate that CloudletScheduler is overwritten
 * by mutableAttributesInit() in VmAbstract constructor.
 */
public class CloudletSchedulerBugExample {
    public static void main(String[] args) {
        var simulation = new CloudSimPlus();

        // Create datacenter with 1 host
        var host = new HostSimple(2048, 10_000, 1_000_000, List.of(new PeSimple(1000)));
        var datacenter = new DatacenterSimple(simulation, List.of(host));

        var broker = new DatacenterBrokerSimple(simulation);

        // Create VM with SpaceShared scheduler
        var vm = new VmSimple(1000, 2, new CloudletSchedulerSpaceShared()); // <-- The scheduler should be preserved, but it is overwritten!

        System.out.println("Immediately after VM creation:");
        System.out.println("  Expected scheduler: CloudletSchedulerSpaceShared");
        System.out.println("  Actual scheduler:   " + vm.getCloudletScheduler().getClass().getSimpleName());

        if (vm.getCloudletScheduler() instanceof CloudletSchedulerSpaceShared) {
            System.out.println("\nSUCCESS: Scheduler is correctly SpaceShared");
        } else {
            System.out.println("\nBUG: Scheduler was overwritten to " +
                             vm.getCloudletScheduler().getClass().getSimpleName());
            System.out.println("Root cause: VmAbstract.mutableAttributesInit() calls setCloudletScheduler(TimeShared)");
        }
    }
}
```

## Expected Behavior
The scheduler passed in the constructor should be preserved.

## Workaround
None available - the scheduler cannot be changed after construction.

## Environment
CloudSim Plus version: 8.5.7
Java version: 25

## Root Cause
In `VmAbstract.java`, the constructor chain calls `mutableAttributesInit()` after `setCloudletScheduler(cloudletScheduler)`:

```java
protected VmAbstract(final long id, final long mipsCapacity, final long pesNumber, final CloudletScheduler cloudletScheduler) {
  // ...
  // Constructor sets the correct scheduler
  setCloudletScheduler(cloudletScheduler);
  // ...
  mutableAttributesInit();
}

/ ...
// mutableAttributesInit() then unconditionally resets it
protected void mutableAttributesInit() {
    // ...
    setCloudletScheduler(new CloudletSchedulerTimeShared()); // <-- BUG in VmAbstract.java:222
    // ...
}
```

---

### PR DESCRIPTION
**Pull request by tgasla**
This pull request makes a small change to the VM initialization logic by removing the default assignment of a `CloudletSchedulerTimeShared` scheduler in the `mutableAttributesInit` method. 

Closes #542.

### CODE REVIEW

File: src/main/java/org/cloudsimplus/brokers/DatacenterBrokerAbstract.java [hunk 1]
```diff
@@ -903,6 +903,7 @@ private boolean processCloudletReturn(final SimEvent evt) {
             getSimulation().clockStr(), getName(), cloudlet, lifeTime, cloudlet.getVm());
 
         if (cloudlet.getVm().getCloudletScheduler().isEmpty()) {
+            ((VmSimple) cloudlet.getVm()).setFreePesNumber(cloudlet.getVm().getPesNumber());
```
Comment (manoelcampos) [inline src/main/java/org/cloudsimplus/brokers/DatacenterBrokerAbstract.java]: Next time, just try to avoid making changes unrelated to the issue.

**Review by manoelcampos — APPROVED** [review]

**Review by manoelcampos — APPROVED** [review]

File: src/main/java/org/cloudsimplus/brokers/DatacenterBrokerAbstract.java (hunk 1 above)
Comment (manoelcampos) [reply src/main/java/org/cloudsimplus/brokers/DatacenterBrokerAbstract.java]: I see the issue here. This change was related to issue #544 and there is a PR already for that (#545).
This way, your PR has commits for different issues. This happened because you fixed the current issue on your master, then you created a new branch for the other issue from master again, that already had the fix for the previous issue.

Check the CONTRIBUTING.md that provides more details on that. Anyway, for each issue, you should create a new topic branch from master. If you are fixing multiple issues at the same time, you should always checkout to master again to create a new branch from there.

Comment (tgasla) [reply src/main/java/org/cloudsimplus/brokers/DatacenterBrokerAbstract.java]: Thanks for checking out the pull request. Yes, as you correctly guessed that's what happened. I should have created a separate branch based on the master branch for each of the bug fixes. I totally forgot about it and accidentally kept working on the same local branch. Apologies for that.

**Comment by manoelcampos** [comment]
@tgasla thanks for your contribution.
